source 'https://rubygems.org'

ruby File.read('.ruby-version').strip

gem 'activerecord-enhancedsqlite3-adapter' , '~> 0.8'
gem 'clearance', '~> 2.8'
gem 'devise', '~> 4.9'
gem 'faker', '~> 3.4'
gem 'importmap-rails', '~> 2.0'
gem 'litestream', '~> 0.11'
gem 'pagy', '~> 9.1'
gem 'propshaft', '~> 1.1.0'
gem 'puma', '~> 6.4'
gem 'rails', '~> 7.2'
gem 'redis', '~> 5.3'
gem 'requestjs-rails', '~> 0.0.12'
gem 'rspec-rails', '~> 7.0'
gem 'scenic', '~> 1.8'
gem 'scenic_sqlite_adapter', '~> 0.1'
gem 'stimulus-rails', '~> 1.3'
gem 'sqlite3', '~> 2.1'
gem 'turbo-rails', '~> 2.0'

group :development do
  gem 'cuprite', '~> 0.15'
  gem 'database_cleaner-active_record', '~> 2.2'
  gem 'debug', '~> 1.9', platforms: %i[mri]
  gem 'dotenv-rails', '~> 3.1'
  gem 'factory_bot_rails', '~> 6.4'
  gem 'hotwire-livereload', '~> 1.4'
  gem 'launchy', '~> 3.0'
  gem 'rails-controller-testing', '~> 1.0'
  gem 'ruby-lsp', '~> 0.20'
  gem 'ruby-lsp-rails', '~> 0.3'
end
