source 'https://rubygems.org'

ruby File.read('.ruby-version').strip

gem 'activerecord-enhancedsqlite3-adapter', '~> 0.8'
gem 'authentication-zero', '~> 4.0' 
gem 'bootsnap', '~> 1.18', require: false
gem 'faker', '~> 3.4'
gem 'importmap-rails', '~> 2.0'
gem 'jbuilder', '~> 2.13'
gem 'litestream', '~> 0.11'
gem 'ostruct', '~> 0.6.0'
gem 'pagy', '~> 9.1'
gem 'propshaft', '~> 1.1.0'
gem 'puma', '~> 6.4'
gem 'rails', '~> 8.0.0'
gem 'requestjs-rails', '~> 0.0.12'
gem 'rspec-rails', '~> 7.0'

# scenic is for versioned database views
gem 'scenic', '~> 1.8'
gem 'scenic_sqlite_adapter', '~> 0.1'

gem 'solid_cable', '~> 3.0'
gem 'solid_cache', '~> 1.0'
gem 'solid_queue', '~> 1.0'
gem 'stimulus-rails', '~> 1.3'
gem 'sqlite3', '~> 2.1'
gem 'turbo-rails', '~> 2.0'

group :development, :test do
  # Security scanner
  gem 'brakeman', '~> 6.2', require: false
  gem 'cuprite', '~> 0.15.1'
  gem 'database_cleaner-active_record'
  gem 'debug', '~> 1.9', platforms: %i[ mri ], require: 'debug/prelude'
  gem 'dotenv-rails', '~> 3.1'
  gem 'factory_bot_rails', '~> 6.4'
  gem 'hotwire-livereload', '~> 1.4'
  gem 'launchy', '~> 3.0'
  gem "rails-controller-testing", "~> 1.0"

end

group :development do
  gem 'web-console'
end

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
gem 'bcrypt', '~> 3.1.7'

gem "css-zero", "~> 0.0.73"
